loss: {
    "train_loss": {
        "rec_loss": {"name": "rec_loss","args": ["pred", "scene_color"],  "mode": "charbonnier_l1", "scale": 1.0, "config": {"tonemap": log}},
        "rec_residual_loss": {"args": ["pred_scene_light_no_st", "scene_light_no_st"],  "mode": "charbonnier_l1", "scale": 1.0, "config": {"tonemap": log, "skybox_mask_out": true}},
        "sky_color_loss": {"args": ["pred_sky_color", "sky_color"], "mode": "charbonnier_l1", "config": {"tonemap": log, "skybox_mask": true}},
        "st_color_loss": {"args": ["pred_st_color", "st_color"], "mode": "charbonnier_l1", "scale": 1.0, "config": {"tonemap": log}},
        "st_alpha_loss": {"args": ["pred_st_alpha", "st_alpha"], "mode": "charbonnier_l1", "config": {}},
    },
    "debug_loss": {
        "psnr": {"args": ["pred", "scene_color"], "mode": "psnr", "config": {"tonemap": aces, "skybox_mask": false}},
        "ssim": {"args": ["pred", "scene_color"], "mode": "ssim", "config": {"tonemap": aces, "skybox_mask": false}},
        # "lpips": {"args": ["pred","scene_color", ], "mode": "lpips", "config": {"tonemap": aces, "skybox_mask": false}},
        "psnr_no_st": {"args": ["pred_scene_color_no_st", "scene_color_no_st"], "mode": "psnr", "config": {"tonemap": aces, "skybox_mask": false}},
        "ssim_no_st": {"args": ["pred_scene_color_no_st", "scene_color_no_st"], "mode": "ssim", "config": {"tonemap": aces, "skybox_mask": false}},
        # "lpips_no_st": {"args": ["pred_scene_color_no_st","scene_color_no_st", ], "mode": "lpips", "config": {"tonemap": aces, "skybox_mask": false}},
        "psnr_st": {"args": ["pred_st_color", "st_color"], "mode": "psnr", "config": {"tonemap": aces, "skybox_mask": false}},
        "ssim_st": {"args": ["pred_st_color", "st_color"], "mode": "ssim", "config": {"tonemap": aces, "skybox_mask": false}},
        # "lpips_st": {"args": ["pred_st_color","st_color", ], "mode": "lpips", "config": {"tonemap": aces, "skybox_mask": false}},
    },
    "test_loss":{
        "psnr": {"args": ["pred", "scene_color"], "mode": "psnr", "config": {"tonemap": aces, "skybox_mask": false}},
        "ssim": {"args": ["pred", "scene_color"], "mode": "ssim", "config": {"tonemap": aces, "skybox_mask": false}},
        "lpips": {"args": ["pred","scene_color", ], "mode": "lpips", "config": {"tonemap": aces, "skybox_mask": false}},
        "psnr_no_st": {"args": ["pred_scene_color_no_st", "scene_color_no_st"], "mode": "psnr", "config": {"tonemap": aces, "skybox_mask": false}},
        "ssim_no_st": {"args": ["pred_scene_color_no_st", "scene_color_no_st"], "mode": "ssim", "config": {"tonemap": aces, "skybox_mask": false}},
        "lpips_no_st": {"args": ["pred_scene_color_no_st","scene_color_no_st", ], "mode": "lpips", "config": {"tonemap": aces, "skybox_mask": false}},
        # "npsnr_st": {"args": ["pred_st_color", "st_color"], "mode": "normalized_psnr", "config": {"tonemap": aces, "skybox_mask": false}},
        "psnr_st": {"args": ["pred_st_color", "st_color"], "mode": "psnr", "config": {"tonemap": aces, "skybox_mask": false}},
        "ssim_st": {"args": ["pred_st_color", "st_color"], "mode": "ssim", "config": {"tonemap": aces, "skybox_mask": false}},
        "lpips_st": {"args": ["pred_st_color","st_color", ], "mode": "lpips", "config": {"tonemap": aces, "skybox_mask": false}},
        "psnr_st_blend": {"args": ["pred_scene_color_st_blend", "scene_color"], "mode": "psnr", "config": {"tonemap": aces, "skybox_mask": false}},
        "ssim_st_blend": {"args": ["pred_scene_color_st_blend", "scene_color"], "mode": "ssim", "config": {"tonemap": aces, "skybox_mask": false}},
        "lpips_st_blend": {"args": ["pred_scene_color_st_blend","scene_color", ], "mode": "lpips", "config": {"tonemap": aces, "skybox_mask": false}},
    },
}
logging:
  scalar_items:
    all: {}
    train:
      he_0_prob:
        name: p0
        fmt: "{:.2g}"
        channels: [bar_epoch, tb_step, tb_epoch, file_step]
      he_1_prob:
        name: p1
        fmt: "{:.2g}"
        channels: [bar_epoch, tb_step, tb_epoch, file_step]
      he_2_prob:
        name: p2
        fmt: "{:.2g}"
        channels: [bar_epoch, tb_step, tb_epoch, file_step]
      rendered_prob:
        name: pr
        fmt: "{:.2g}"
        channels: [bar_epoch, tb_step, tb_epoch, file_step]
      lr:
        fmt: "{:.3e}"
        channels: [bar_step, tb_step, file_step]
      loss:
        fmt: "{:.3e}"
        channels: [bar_step, bar_epoch, tb_step, tb_epoch, file_step]
      rec_loss:
        fmt: "{:.3e}"
        channels: [tb_step, tb_epoch, file_step]
      rec_residual_loss:
        fmt: "{:.3e}"
        channels: [tb_step, tb_epoch, file_step]
      rec_residual_color_census_loss:
        fmt: "{:.3e}"
        channels: [tb_step, tb_epoch, file_step]
      rec_st_color_census_loss:
        fmt: "{:.3e}"
        channels: [tb_step, tb_epoch, file_step]
      residual_item_loss:
        fmt: "{:.3e}"
        channels: [tb_step, tb_epoch, file_step]
      sky_color_loss:
        fmt: "{:.3e}"
        channels: [tb_step, tb_epoch, file_step]
      st_color_loss:
        fmt: "{:.3e}"
        channels: [tb_step, tb_epoch, file_step]
      st_alpha_loss:
        fmt: "{:.3e}"
        channels: [tb_step, tb_epoch, file_step]
      zero_flow_loss:
        fmt: "{:.3e}"
        channels: [tb_step, tb_epoch, file_step]
      zero_flow2_loss:
        fmt: "{:.3e}"
        channels: [tb_step, tb_epoch, file_step]
      c1_flow_loss:
        fmt: "{:.3e}"
        channels: [tb_step, tb_epoch, file_step]
      psnr:
        fmt: "{:.5g}"
        channels: [bar_step, bar_epoch, tb_step, tb_epoch, file_step, file_epoch]
      ssim:
        fmt: "{:.5g}"
        channels: [tb_step, tb_epoch, file_step, file_epoch]
      lpips:
        fmt: "{:.5g}"
        channels: [tb_step, tb_epoch, file_step, file_epoch]
      psnr_no_st:
        fmt: "{:.5g}"
        channels: [bar_step, bar_epoch, tb_step, tb_epoch, file_step, file_epoch]
      ssim_no_st:
        fmt: "{:.5g}"
        channels: [tb_step, tb_epoch, file_step, file_epoch]
      lpips_no_st:
        fmt: "{:.5g}"
        channels: [tb_step, tb_epoch, file_step, file_epoch]
      psnr_st:
        fmt: "{:.5g}"
        channels: [bar_step, bar_epoch, tb_step, tb_epoch, file_step, file_epoch]
      ssim_st:
        fmt: "{:.5g}"
        channels: [tb_step, tb_epoch, file_step, file_epoch]
      lpips_st:
        fmt: "{:.5g}"
        channels: [tb_step, tb_epoch, file_step, file_epoch]
    test:
      psnr:
        fmt: "{:.5g}"
        channels: [bar_step, bar_epoch, tb_step, tb_epoch, file_step, file_epoch]
      ssim:
        fmt: "{:.5g}"
        channels: [tb_step, tb_epoch, file_step, file_epoch]
      lpips:
        fmt: "{:.5g}"
        channels: [tb_step, tb_epoch, file_step, file_epoch]
      psnr_no_st:
        fmt: "{:.5g}"
        channels: [bar_step, bar_epoch, tb_step, tb_epoch, file_step, file_epoch]
      ssim_no_st:
        fmt: "{:.5g}"
        channels: [tb_step, tb_epoch, file_step]
      lpips_no_st:
        fmt: "{:.5g}"
        channels: [tb_step, tb_epoch, file_step]
      psnr_st:
        fmt: "{:.5g}"
        channels: [bar_step, bar_epoch, tb_step, tb_epoch, file_step, file_epoch]
      ssim_st:
        fmt: "{:.5g}"
        channels: [tb_step, tb_epoch, file_step, file_epoch]
      lpips_st:
        fmt: "{:.5g}"
        channels: [tb_step, tb_epoch, file_step, file_epoch]
      psnr_st_blend:
        fmt: "{:.5g}"
        channels: [bar_step, bar_epoch, tb_step, tb_epoch, file_step, file_epoch]
      ssim_st_blend:
        fmt: "{:.5g}"
        channels: [tb_step, tb_epoch, file_step, file_epoch]
      lpips_st_blend:
        fmt: "{:.5g}"
        channels: [tb_step, tb_epoch, file_step, file_epoch]
