job_name: "month_day/version_modelname_settings"
config_root_path: "config/"
base: null
pipeline: [
  # "export/export.yaml"
]
include: [
  "includes/dataset_export_job.yaml",
]
train_parameter:
  optimizer: 
    type: AdamW
    weight_decay: 0.0
    betas: [0.9, 0.999]
  gradient_accumulation_steps: 1
  amp: false
  train_precision_mode: "fp32"
  test_precision_mode: "fp32"
  epoch: 150
  batch_size: 6
  decay_at: !!float 1.0
  lr_config:
    initial_lr: !!float 1e-4
detect_anomaly: false
output_root_path: "../output/train_output/"
debug: false
log_to_file: true
clear_output_path: false
runtime:
  cuda_visible_devices: []
dataset:
  type: ""
  train_precision_mode: "fp16"
  test_precision_mode: "fp16"
  # recurrent_train: true,
  # recurrent_test: true,
  # recurrent_train_start: 0.5,
  # brdf_demodulate: true
  # for compatibility for old version config
  flip: false
  shuffle_metadata: false
  shuffle_loader: false
  pin_memory: false
  path: ""
  train_num_worker_sum: 6
  test_num_worker: 1
  mode: "sep"
  train_scale: 1.0
  is_block: false
  block_size: 8
  train_scene: []
  test_scene: []
  part: []
  history_config: {}
  future_conifg: null
trainer:
  type: ""
  num_gpu: 0
  wait_to_start: "0"
  debug_data_flow: true
  ddp__find_unused_parameters: false
loss:
  type: "LossFunction"
  train_loss: {}
  debug_loss: {}
logging:
  targets:
    tb: { type: tensorboard, enable: true }
    console_inline: { type: console, enable: true, args: { mid: ", " } }
    console_lines: { type: console, enable: true, args: { mid: "\n" } }
    file_inline: { type: log_file, enable: true, args: { mid: ", " } }
    file_lines: { type: log_file, enable: true, args: { mid: "\n" } }
    bar: { type: bar, enable: true }
    ckpt: { type: state_dict, enable: true, args: { path: checkpoint_path, clear_latest: true } }
    ckpt_hist: { type: state_dict, enable: true, args: { path: history_checkpoint_path } }
    model: { type: state_dict, enable: true, args: { path: model_path, clear_latest: true } }
    model_best: { type: state_dict, enable: true, args: { path: best_model_path, clear_latest: true } }
    model_hist: { type: state_dict, enable: true, args: { path: history_model_path } }
  scalar_items:
    all: {}
    train:
      loss:
        name: loss
        fmt: "{:.5e}"
        channels: [tb_step, tb_epoch, bar_step, bar_epoch, console_step, console_epoch, file_step, file_epoch]
    test:
      psnr:
        name: psnr
        fmt: "{:.5g}"
        channels: [tb_epoch, bar_epoch, console_epoch, file_epoch]
  routes:
    all:
      - channel: init_info
        event: init
        trigger: { type: once }
        collect: { type: text, source: init_info, args: { tag: "info" } }
        targets: [tb, file_lines]
      - channel: step_info
        event: init
        trigger: { type: once }
        collect: { type: text, source: step_info, args: { tag: "log" } }
        targets: [file_lines]
    train:
      - channel: tb_step
        event: step_end
        trigger: { type: epoch_times, times: 200, spacing: log, offset: 1 }
        collect: { type: scalars, source: scalars }
        targets: [tb]
      - channel: bar_desc_step
        event: step_end
        trigger: { type: step_interval, every: 1, offset: 0 }
        collect: { type: bar, source: bar_desc }
        targets: [bar]
      - channel: file_step
        event: step_end
        trigger: { type: epoch_times, times: 200, spacing: log, offset: 1 }
        collect: { type: text, source: text, args: { tag: "train_step" } }
        targets: [file_inline]
      - channel: console_step
        event: step_end
        trigger: { type: step_interval, every: 8, offset: 1 }
        collect: { type: text, source: text, args: { tag: "train_step" } }
        targets: [console_lines]
      - channel: debug_data_step
        event: step_end
        trigger: { type: step_interval, every: 1, offset: 0 }
        collect: { type: text, source: debug_data_step, args: { tag: "debug_step" } }
        targets: [console_lines]
      - channel: bar_step
        event: step_end
        trigger: { type: epoch_times, times: 50, spacing: log, offset: 1 }
        collect: { type: bar, source: bar }
        targets: [bar]
      - channel: tb_images_step
        event: step_end
        trigger: { type: epoch_times, times: 10, spacing: log, offset: 1 }
        collect: { type: images, source: images }
        targets: [tb]

      - channel: tb_epoch
        event: epoch_end
        trigger: { type: epoch_interval, every: 1, offset: 0 }
        collect: { type: scalars, source: scalars }
        targets: [tb]
      - channel: file_epoch
        event: epoch_end
        trigger: { type: epoch_interval, every: 1, offset: 0 }
        collect: { type: text, source: text, args: { tag: "train_epoch" } }
        targets: [file_inline]
      - channel: console_epoch
        event: epoch_end
        trigger: { type: epoch_interval, every: 1, offset: 0 }
        collect: { type: text, source: text, args: { tag: "train_epoch" } }
        targets: [console_inline]
      - channel: bar_epoch
        event: epoch_end
        trigger: { type: epoch_interval, every: 1, offset: 0 }
        collect: { type: bar, source: bar }
        targets: [bar]

      - channel: checkpoint_epoch
        event: epoch_end
        trigger: { type: epoch_interval, every: 1, offset: 0 }
        collect: { type: state_dict, source: state_dict_checkpoint_epoch }
        targets: [ckpt]
      - channel: checkpoint_history_epoch
        event: epoch_end
        trigger: { type: epoch_interval, every: 1, offset: 0 }
        collect: { type: state_dict, source: state_dict_checkpoint_history_epoch }
        targets: [ckpt_hist]
      - channel: models_epoch
        event: epoch_end
        trigger: { type: epoch_interval, every: 1, offset: 0 }
        collect: { type: state_dict, source: models_last_epoch }
        targets: [model]
      - channel: models_best_epoch
        event: epoch_end
        trigger: { type: epoch_interval, every: 1, offset: 0 }
        collect: { type: state_dict, source: models_best_epoch }
        targets: [model_best]
      - channel: models_history_epoch
        event: epoch_end
        trigger: { type: epoch_interval, every: 1, offset: 0 }
        collect: { type: state_dict, source: models_history_epoch }
        targets: [model_hist]
    test:
      - channel: tb_epoch
        event: epoch_end
        trigger: { type: epoch_interval, every: 1, offset: 0 }
        collect: { type: scalars, source: scalars }
        targets: [tb]
      - channel: file_epoch
        event: epoch_end
        trigger: { type: epoch_interval, every: 1, offset: 0 }
        collect: { type: text, source: text, args: { tag: "test_epoch" } }
        targets: [file_inline]
      - channel: console_epoch
        event: epoch_end
        trigger: { type: epoch_interval, every: 1, offset: 0 }
        collect: { type: text, source: text, args: { tag: "test_epoch" } }
        targets: [console_inline]
      - channel: bar_epoch
        event: epoch_end
        trigger: { type: epoch_interval, every: 1, offset: 0 }
        collect: { type: bar, source: bar }
        targets: [bar]
model:
  model_name: "instance_model_name"
  type: ""
  precision: "fp32"
  inference_precision: "fp32"
  




  


